name: stripedart
description: Dart library for the Stripe API. The Stripe Dart library provides convenient access to the Stripe API from applications written in server-side Dart.
version: 1.0.0
homepage: https://github.com/LucaIaconelli/stripe_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  json_annotation: ^3.0.0

dev_dependencies:
  test: ^1.14.3
  json_serializable: ^3.3.0
  build_runner: ^1.0.0